apiVersion: v1
kind: Service
metadata:
  name: devfinops-flet-app-service
  namespace: devfinops
spec:
  selector:
    app: devfinops-flet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer